FlyingChairsBasePath = 'datasets/FlyingChairs/FlyingChairs_release/data/'
FlyingChairsMetaFilePath = 'datasets/FlyingChairs/FlyingChairs_train_val.txt'
FlyingThingsBasePath = 'datasets/FlyingThings'
KITTIBasePath = 'datasets/KITTI/'
SintelBasePath = 'datasets/Sintel'
SintelFullsetBasePath = 'datasets/Sintel/png'
SpringBasePath = 'datasets/Spring'
HD1kBasePath = 'datasets/hd1k_full_package'